name: Release Extension

on:
  release:
    types: [published]


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: "npm ci"

      - name: Update version
        run: npm version ${{ github.event.release.tag_name }} ----no-git-tag-version

      - name: Publish
        run: vsce publish --pat ${{ secrets.VS_MARKETPLACE_TOKEN }} --no-git-tag-version --no-update-package.json
